require "user.options"
require "user.packages"
require "user.lualine"
require "user.keymaps"
require "user.colorscheme"
require "user.cmp"
require "user.nvim-tree"
require "user.telescope"
require "languages"
require "user.whichkey"
require "user.comment"
require "user.mason"
require "user.treesitter"
require "user.autopairs"
-- require "user.gitsigns"
require "user.bufferline"
-- require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
-- require "user.alpha"
require "user.autocommands"
